### ISSUE TITLE
Feature request: improve request preview

### ISSUE THREAD

**Issue by zhaogangang** [rest-nvim/rest.nvim#103]
may suppert import curl into some file or another window?, preview curl in command line which  can't copy and not easy to see more detail

**Comment by NTBBloodbath** [comment]
I think I'll add a functionality to copy cURL preview command into a register _and also to clipboard_ and this should be fine so you could just paste it into any other place to get reproducible runs of your http tests.

**Comment by udayvir-singh** [comment]
I had the same issue which was fixed with #125, in which I replaced `vim.notify` with `nvim_echo` for better readability.

![2022-09-13-170641_1920x1080_scrot](https://user-images.githubusercontent.com/97400310/189891255-dffb9deb-16f7-4a75-9acd-e1089a87a930.png)
