### ISSUE TITLE
Sending JSON-payload

### ISSUE THREAD

**Issue by diskriminantti** [rest-nvim/rest.nvim#114]
Hello! I just installed this plugin, and it works pretty well so far! I'm having some issues though, not sure if I'm understanding this plugin correctly. I'm trying to send some data as json, like this:

```
POST http://httpbin.org/post
Content-Type: application/json

{ "name": "Test"}
```

I get a response like this in the response window:
```
POST http://httpbin.org/post
Content-Type: application/json

{
  "args": {},
  "data": "name=Test",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "deflate, gzip, br",
    "Content-Length": "9",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.68.0",
  },
  "json": null,
  "origin": "XXX.XXX.XXX.XXX",
  "url": "http://httpbin.org/post"
}

```

I was expecting to get the same data back in the `json` -field of the response, but it's `null` as you can see. I checked the output of `RestNvimPreview` and it gave me this: ` curl -sSL --compressed -X 'POST' -H 'Content-Type: application/json' -d 'name=Test' 'http://httpbin.org/post'` . Trying to send that from the command line gives me the same response as before. 

I kinda figured with the `Content-Type` header, the data would be sent as json, but it seems like that's not the case. Is this intended behavior, or have I misunderstood something? It's a great plugin nonetheless, thanks for creating it!

**Comment by jceb** [comment]
Same here. The issue comes from plenary. It doesn't seem to support JSON. Instead, it generates `=` separated entries that are sent over the wire. See https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/curl.lua#L108

The issue was caused by commit 33c6829c8b612e92b731d8ff7c8b96a05afa1642. Instead of a string, a table is returned which triggers plenary's behavior.

**Comment by diskriminantti** [comment]
Thanks for the heads up! At least for now, I reverted back to commit `e5f68db73276c4d4d255f75a77bbe6eff7a476ef` which works as expected.

**Comment by jackpinto** [comment]
Same here! Is there any workaround for it?

**Comment by kennycallado** [comment]
Same here!

**Comment by srihari93** [comment]
@NTBBloodbath Please revert merging my latest [PR](https://github.com/NTBBloodbath/rest.nvim/pull/113), It is the root cause for the issue.

**Comment by nagy135** [comment]
any progress on this ? I remember reading that maintainer is done with this repo (on reddit) and this would correlate with 12 old last commit. Any forks if so ?

**Comment by thaiducdung255** [comment]
> any progress on this ? I remember reading that maintainer is done with this repo (on reddit) and this would correlate with 12 old last commit. Any forks if so ?

You can consider this fork to resolve this issue: https://github.com/teto/rest.nvim/tree/always-send-string
It works for me :)

**Comment by Emptyfruit** [comment]
I just installed the plugin for the first time and have this bug.
Neovim 0.8.1

**Comment by rochacbruno** [comment]
Headers on `POST` must be lower case

```diff
- Content-Type: application/json
+ content-type: application/json
```
