### ISSUE TITLE
RFC 2616 not followed completely

### ISSUE THREAD

**Issue by MarcThu** [rest-nvim/rest.nvim#121]
Thanks for your work so far! I really like the idea of this plugin. It's one step ahead to use nvim as a complete IDE.

But if I am right, rest.nvim does not follow the RFC 2616 format completely.

The following request does not work, but should according to [RFC](https://datatracker.ietf.org/doc/html/rfc2616#section-14.23):
```HTTP
GET /pub/WWW/ HTTP/1.1
Host: www.w3.org


```

It gets wrapped to: 
```BASH
curl -sSL --compressed -X 'GET' -H 'Host: www.w3.org' --data-raw '' '/pub/WWW/+HTTP/1.1'
```

But it should get wrapped to:
```BASH
curl -X 'GET' www.w3.org/pub/WWW/
```

Or am I missing something?

**Comment by PinpongTp** [comment]
Hi @MarcThu @NTBBloodbath 

Please review my PR.
It supports for requires by HTTP protocol version and Host request-header like this
``` HTTP
GET /pub/WWW/ HTTP/1.1
Host: www.w3.org
```
Thank you.
It is my first issue.
