### ISSUE TITLE
how to run the tests ?

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#135]
I can run the tests manually but didnt find a way to run them automatically. Running them on CI would make merging PRs less dangerous . @NTBBloodbath how do you run them ?

**Comment by NTBBloodbath** [comment]
Hmm I used to run them one by one manually. Maybe we could expose a Lua function to run a whole tests file(s) so we can run them all in a shot for this purpose?

The thing is that we would also have to return an exit code other than 0 in case a test fails, right? If so, would using an `os.exit(code)` suffice?

**Comment by teto** [comment]
anything that can detect an error, and ideally which one. neovim uses busted to run tests and plenary has also some helpers to run tests.

**Comment by teto** [comment]
I am looking into this. Seems like I will need to fork busted though :)

**Comment by teto** [comment]
I've created https://github.com/rest-nvim/rest.nvim/pull/159 which I hope can help people add some tests.

**Comment by teto** [comment]
this is now documented in READMe
