### ISSUE TITLE
Curl client

### ISSUE THREAD

**Issue by crisAbexus** [rest-nvim/rest.nvim#145]
Hey, thanks for the plugin, it's absolutely satisfying to use.
Can you enable a way to use direct curl commands?, I mean instead of use the regular request syntax just draft a request like:
curl https://reqres.in/api/users?page=5 -H "Cache-Control: must-revalidate" -H "Pragma: no-cache" -H "Expires: 0"

**Comment by NTBBloodbath** [comment]
Closing as not planned, because it is not doable with the current cURL implementation which uses native bindings instead of manually spawning the cURL command-line utility.
