### ISSUE TITLE
remove the usage of goto

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#155]
goto is not available in lua 5.1 (it is in lua 5.2) : 
https://github.com/rest-nvim/rest.nvim/blob/2e368cd681379f014906ad0268111eb5c95f9aa6/lua/rest-nvim/request/init.lua#L114

so it broke some of my tests. It works with luajit though but I dont think we should require luajit just for a goto @jens1205

**Comment by NTBBloodbath** [comment]
I think we could just rewrite logic from [request/init.lua#L112-L122](https://github.com/rest-nvim/rest.nvim/blob/main/lua/rest-nvim/request/init.lua#L112-L122) to not require that goto statement, it's basically changing first conditional and embedding the rest of the loop code on it.

**Comment by NTBBloodbath** [comment]
Closing as resolved, `rest.nvim`'s v2 is no longer using goto statements :)

**Comment by teto** [comment]
haha that was the issue I was thinking of in the chat ^^
