### ISSUE TITLE
Issue when using wildcard in URL

### ISSUE THREAD

**Issue by jmlucjav** [rest-nvim/rest.nvim#161]
Hi

I can use this against a Elasticsearch endpoint in AWS:

```
GET {{URL}}/_cat/indices
Cookie: iam={{TOKEN}}
```

We do some auth thing with the cookie, all works well. But if I add some wildcard to the url, which is still a valid url in Elasticsearch, it stops working:

```
GET {{URL}}/_cat/indices/*
Cookie: iam={{TOKEN}}
```

  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details..."

I I remove the wildcards, the requests succeeds. Could this be something to do with encodings?

I am using the plugin as of a week ago.
thanks!

**Comment by Shadesfear** [comment]
issue stil seems to be present. Is there an update on this?

**Comment by boltlessengineer** [comment]
This might be issue with url encoding feature.
You can disable auto url encoding from `request.hooks.encode_url` option.
Closing this issue. Feel free to reopen this if it still happens
