### ISSUE TITLE
Disable debug logs?

### ISSUE THREAD

**Issue by ray-x** [rest-nvim/rest.nvim#164]
Is it possible to disable debug logs, some debug logs are not very helpful for user.
e.g.
```
[rest.nvim] [DEBUG 14:43:41] ...pack/packer/opt/rest.nvim/lua/rest-nvim/request/init.lua:179: Searching pattern starting from 23
```

**Comment by teto** [comment]
that's because the log level is hardcoded to debug: `local log = require("plenary.log").new({ plugin = "rest.nvim", level = "debug" })`
which should not be the case but controlled via `DEBUG_PLENARY="debug"`

**Comment by teto** [comment]
can you check if https://github.com/rest-nvim/rest.nvim/pull/166 fixes your issue ?

**Comment by ray-x** [comment]
It works. I suppose the PR will merge shortly and I am closing the isuue.
