### ISSUE TITLE
query separator `---` is sometimes used as a curl argument

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#172]
when testing https://github.com/rest-nvim/rest.nvim/pull/122, I realized some failures were due to `---` being used as a curl argument. 
Parsing the queries by "hand" is too error-prone. I hope a fix comes from a better usage of the treesitter grammer.

**Comment by teto** [comment]
seems like that behavior is kinda LGTM or rather `---` is not a query separator as I expected. I've played a bit with the treesitter grammar and it's promising, could definitely improve the situation.

**Comment by h3ndry** [comment]
Hello, How do I pass curl args ?

**Comment by PhilRunninger** [comment]
Hi @h3ndry,

It seems to be that a blank line is required to find the end of the headers. After that blank line, is where the curl args go. Issue #198 describes a situation that makes that blank line appear optional, but I believe it's best to include it. Here's an example.

```http
POST https://reqres.in/api/users
Content-Type: application/json

--silent

{
    "name": "morpheus",
    "job": "leader",
    "array": ["a", "b", "c"],
    "object_ugly_closing": {
      "some_key": "some_value"
  }
}

# The next query works only because of a bug - issue #198. Proper syntax
# requires blank line before curl args.
GET https://reqres.in/api/users
--silent
```
