### ISSUE TITLE
how to figure out current selected json env

### ISSUE THREAD

**Issue by shalei6698** [rest-nvim/rest.nvim#176]
I have two json env, .cmp-pre.json, .cmp-production.json
when test diffrent env api, i use RestSelectEnv exchange env file very often
then i cant figure out which env the response from, is there any way to show selected env_file on the  winbar or other visible place?

![image](https://user-images.githubusercontent.com/5708724/212640390-89c9149f-044d-4a90-a765-3f0384976362.png)

**Comment by teto** [comment]
cc @D-James-GH our environment specialist

**Comment by D-James-GH** [comment]
There is not currently a display for the selected ENV. But I do think this would be a useful addition!
