### ISSUE TITLE
Trailing `==` gets removed from variable value

### ISSUE THREAD

**Issue by mawkler** [rest-nvim/rest.nvim#177]
When pressing `<Plug>RestNvimPreview` on the following example

```http
@key = foobarbaz==

GET http://foo
x-functions-key: {{key}}
```

the following is printed:

```sh
curl -sSL --compressed -X 'GET' -H 'X-Functions-Key: foobarbaz' --data-raw 'x-functions-key: foobarbaz' 'http://foo'
```

Notice that `foobarbaz` in `X-Functions-Key: foobarbaz` doesn't have the trailing `==`.

This is the output that I expect:

```sh
curl -sSL --compressed -X 'GET' -H 'X-Functions-Key: foobarbaz==' --data-raw 'x-functions-key: foobarbaz==' 'http://foo'
```

**Comment by flexagoon** [comment]
Variables are now required to be wrapped in quotes, so this issue is no longer relevant

@mawkler @NTBBloodbath
