### ISSUE TITLE
Not working in brand new install

### ISSUE THREAD

**Issue by dimas-cyriaco** [rest-nvim/rest.nvim#183]
I just installed with the README instructions, and I get the following error when trying to execute the following request:

```
GET https://google.com
```

```
E5108: Error executing lua ...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:23: '' is not a valid language name
stack traceback:
	[C]: in function 'error'
	...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:23: in function 'require_language'
	...3/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:38: in function '_create_parser'
	...3/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
	...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:193: in function 'read_document_variables'
	...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:224: in function 'read_variables'
	...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:234: in function 'replace_vars'
	...share/nvim/lazy/rest.nvim/lua/rest-nvim/request/init.lua:276: in function 'parse_url'
	...share/nvim/lazy/rest.nvim/lua/rest-nvim/request/init.lua:309: in function 'get_current_request'
	.../.local/share/nvim/lazy/rest.nvim/lua/rest-nvim/init.lua:18: in function 'run'
	[string ":lua"]:1: in main chunk
```

I have all the Treesitter parses installed:

```
html              [✓] installed
http              [✓] installed
json              [✓] installed
json5             [✓] installed
jsonc             [✓] installed
```

Any idea what's the problem?

**Comment by dimas-cyriaco** [comment]
I realized the plugin is not setting the buffer filetype automatically. If I set the buffer filetype with `set filetype=http` the syntax highlight works, but the request still fails. Now with error:

```
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:259: get https://google.com - curl error exit_code=92 stderr={ "curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:259: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:240: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:46: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:37>
```

**Comment by dimas-cyriaco** [comment]
It woks this `htts`  (not `https`) requests.

I'll close this, as it seems to be a bug on `plenary`.

**Comment by NTBBloodbath** [comment]
Hey, this shouldn't be happening. Does the [basic tests](https://github.com/rest-nvim/rest.nvim/blob/main/tests/basic_get.http) works?

If not then this is probably a cURL error on itself or something like that, as it should be working with both `http` and `https` protocols.

**Comment by dimas-cyriaco** [comment]
Ok, it's working with `https` too.
It's seems to be a problem with the filetype not being set. Once I set it manually all works well.
Maybe I should open another issue for this?

**Comment by NTBBloodbath** [comment]
> Ok, it's working with `https` too.
> It's seems to be a problem with the filetype not being set. Once I set it manually all works well.
> Maybe I should open another issue for this?

Sure thing, that way we keep track of it without polluting this one :p
