### ISSUE TITLE
New update from nvim-treesitter breaks http syntax highlight

### ISSUE THREAD

**Issue by dakennguyen** [rest-nvim/rest.nvim#191]
Hi,

since [this commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/c44a63ffdc213a5b56685a34502a00f56a2d061e) I encounter this error whenever I go to HTTP file 
![image](https://user-images.githubusercontent.com/18320285/233611879-3db90e40-87c5-485d-96ba-64d025789256.png)

This is the minimal config to reproduce the issue:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
  {
    'nvim-treesitter/nvim-treesitter',
    commit = "eedc5198a1b4bb1b08ae6d4f64f3d76e376957aa", -- remove this line to cause error
    build = ":TSUpdate",
    opts = {
      ensure_installed = { 'http' },
      highlight = {
        enable = true,
      }
    },
    config = function(_, opts)
      require('nvim-treesitter.configs').setup(opts)
    end,
  },
  'NTBBloodbath/rest.nvim',
}

require("lazy").setup(plugins, {})
```

Here is the maintainer's suggestion: 
> `rest.nvim` specific captures have been removed; they should be added in that plugin (as an `; extends`) query. Please open an issue on that repo.

**Comment by G0V1NDS** [comment]
Created issue for same in here https://github.com/rest-nvim/tree-sitter-http/issues/11

**Comment by NTBBloodbath** [comment]
Hey, I've finally managed to address this issue. See [tree-sitter-http#11 comment](https://github.com/rest-nvim/tree-sitter-http/issues/11#issuecomment-1535495366).

Queries have been updated here too, so they will probably break if you've pinned your http tree-sitter parser using an older commit, please check it out and let me know if the issue persists.

Cheers

**Comment by dakennguyen** [comment]
Hi @NTBBloodbath, thank you for the update!
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/18320285/236423325-26419365-becf-4831-b001-ade31ded1556.png">
For me the env variable doesn't work anymore

**Comment by zhangddjs** [comment]
I also encountered into this issue

**Comment by KyrillGobber** [comment]
Just updated my plugins yesterday and now I also run into this. Syntax highlighting won't work, and it even corrupts my session as soon as I enter a http file and I have to :SessionDelete.
But this is a treesitter issue I believe, right?

**Comment by volga629-1** [comment]
I get error 

```

E5108: Error executing lua ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'conf' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:98: in function 'new'
        ...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        ...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        ...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:218: in function 'read_document_variables'
        ...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:250: in function 'read_variables'
        ...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:260: in function 'replace_vars'
        ...share/nvim/lazy/rest.nvim/lua/rest-nvim/request/init.lua:253: in function 'parse_url'
        ...share/nvim/lazy/rest.nvim/lua/rest-nvim/request/init.lua:286: in function 'get_current_request'
        .../.local/share/nvim/lazy/rest.nvim/lua/rest-nvim/init.lua:25: in function 'run'
        [string ":lua"]:1: in main chunk
```

Structure 

```
.rest
   | .env
   |
   dev-1.rest
```

**Comment by NTBBloodbath** [comment]
> I get error
> 
> ```
> 
> E5108: Error executing lua ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'conf' language, see :help treesitter-parsers
> stack traceback:
>         [C]: in function 'error'
>         ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'
>         ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:98: in function 'new'
>         ...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
>         ...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
>         ...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:218: in function 'read_document_variables'
>         ...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:250: in function 'read_variables'
>         ...l/share/nvim/lazy/rest.nvim/lua/rest-nvim/utils/init.lua:260: in function 'replace_vars'
>         ...share/nvim/lazy/rest.nvim/lua/rest-nvim/request/init.lua:253: in function 'parse_url'
>         ...share/nvim/lazy/rest.nvim/lua/rest-nvim/request/init.lua:286: in function 'get_current_request'
>         .../.local/share/nvim/lazy/rest.nvim/lua/rest-nvim/init.lua:25: in function 'run'
>         [string ":lua"]:1: in main chunk
> ```
> 
> Structure
> 
> ```
> .rest
>    |  .env
>    |  dev-1.rest
> ```

Hey, this is odd.

1. Are you using a `.http` file?
2. Are you lazy-loading `rest.nvim` somehow?

**Comment by volga629-1** [comment]
No lazy loading and I tried http and rest extensions, http give error http and rest give error conf

**Comment by MZAWeb** [comment]
Same problem here. I made it work by forcing the filetype to httpResult, but it's spotty and inconsistent. I can't figure out how to replicate the fix, weirdly.

**Comment by MZAWeb** [comment]
I'm pretty sure it broke on neovim 0.9.4 with this diff https://github.com/neovim/neovim/commit/c5b9643bf1b0f6d5166b4abf6a7c3f29532aefeb

For some reason there's no treesitter parser for http files.

**Comment by MZAWeb** [comment]
> No lazy loading and I tried http and rest extensions, http give error http and rest give error conf

@volga629-1 try ensuring the http treesitter parser is installed

**Comment by volga629-1** [comment]
Thank you for reply, indeed I reinstalled plugin and make sure set 

```
ensure_installed = {
        "http",
```
