### ISSUE TITLE
RFC 2616/7230 and interoperability with other editors/IDEs

### ISSUE THREAD

**Issue by gautaz** [rest-nvim/rest.nvim#205]
Hello,

Looking at the current ecosystem regarding [HTTP requests in editor](https://github.com/JetBrains/http-request-in-editor-spec), my understanding is that the overall goal is to be able to share HTTP requests in a file format that can be later used by any editor/IDEs.

There are some gray areas where this goal seems unreachable, mainly around everything related to reusing data from one request to another.

The current solutions to this I have looked at are:

* using [response scripts (Lua)](https://github.com/rest-nvim/rest.nvim/blob/5714b71120622a3ba64c8784cf29073a45528161/doc/rest-nvim.txt#L167) for [rest-nvim](https://github.com/rest-nvim/rest.nvim)
* using [scripting (NodeJS)](https://httpyac.github.io/guide/scripting.html) for [httpYac](https://httpyac.github.io/)
* using [Request Variables](https://github.com/Huachao/vscode-restclient#request-variables) for [vscode-restclient](https://github.com/Huachao/vscode-restclient)

I have not seen any "standard" way to deal with this issue.
It feels like RFC 2616 has to be extended to be able to reuse data but using broad languages (Lua/Javascript) to achieve this goal seems to miss the point of interoperability.
The `vscode-restclient` approach with its "Request Variables" DSL seems more focused on dealing with this issue.

Has anyone any insight on this matter?
Did anyone find somewhere a "standard" way to deal with reusing data between requests?

**Comment by gautaz** [comment]
Hello @NTBBloodbath, what is your opinion regarding [this statement that JS should be the language of choice for scripting](https://github.com/JetBrains/http-request-in-editor-spec/issues/18#issuecomment-1589235514)?

If this is the way to go, how would that be implemented in `rest.nvim`?

**Comment by wekempf** [comment]
See also https://github.com/dotnet/AspNetCore.Docs/issues/29431. If they start a process for defining a "standard" I'd suggest participating.

**Comment by gautaz** [comment]
> If they start a process for defining a "standard" I'd suggest participating.

Agreed, there is only one point I am wondering about: who is "they"? ;-).

Is there any identified W3C effort which revolves around this type of subject?

**Comment by wekempf** [comment]
I put "standard" in quotes for a reason. I don't believe there's any standardization body considering this. "They" would be the various tool "vendors" (in quotes because some of the tools are OpenSource). As far as I know, aside from that other thread that I started there's been no real movement yet, which is why I said "if they start". I'll continue to apply pressure wherever I can, as I think we have a need for ensuring interoperability between tools.

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
