### ISSUE TITLE
provide a "stable" branch that follows neovim releases

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#206]
and let master for those who follow nightly.
The idea being that users should use tagged releases anyway but until we get better at release management (with proper testing), I suppose users will keep following the git repo, hence the creation of that stable branch.

This started because my linters would emphasize issues with master's code that doesn't follow the nightly API, for instance https://github.com/rest-nvim/rest.nvim/pull/201

cc @NTBBloodbath @D-James-GH

**Comment by boltlessengineer** [comment]
Closing this as rest.nvim now supports neovim v0.10.1 (which is current stable release.)
If there is code using nightly feature, that is a bug and should be fixed from separate issue/prs.
