### ISSUE TITLE
How to escape curly bracket?

### ISSUE THREAD

**Issue by dakennguyen** [rest-nvim/rest.nvim#209]
Hi, I want to send a request like this
```http
POST http://localhost:8000/api/v1/messages
Content-Type: application/json

{
    "template": "{{#user~}}I want a response to the following query:{{query}}{{~/user}}"
}
```

I got this error `Environment variable '#user~' was not found.`
In Insomnia I can put raw string with this 
```
"{% raw %}{{#user~}}I want a response to the following query:{{query}}{{~/user}}{% endraw %}"
``` 
How to achieve the same result with rest.nvim?

**Comment by boltlessengineer** [comment]
One solution would be to use external body.
put your json body to separate file like `./example.json` and include that with external body syntax like this:

```http
POST http://localhost:8000/api/v1/messages
Content-Type: application/json

< ./example.json
```

**Comment by jmbeach** [comment]
This actually didn't work for me. The curly braces still get escaped. I'm on version 3.12.0.
