### ISSUE TITLE
log more 

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#220]
there are a bunch of errors that are not logged, for instance:
```
vim.api.nvim_err_writeln("[rest.nvim]: Last request not found")
```
is added to messages but missing from the plenary log.

I wish neovim's messages was more useful but until we get a neovim refactor in that area, we need to work our way around it via some kind of wrapper maybe.

**Comment by boltlessengineer** [comment]
Closing this due to v3 release. Now rest.nvim don’t use plenary and the logger module is rewritten now.
