### ISSUE TITLE
Semicolon in URL gets undesirably encoded

### ISSUE THREAD

**Issue by mawkler** [rest-nvim/rest.nvim#240]
I have to send a request to a URL with a semicolon in it. However, the semicolon gets encoded into `%3B`. The request only works if the literal `;` is in the URL. Here's an example to illustrate:

```http
GET https://duckduckgo.com/foo;bar
```

Becomes this:

```sh
curl -sSL --compressed -X 'GET' 'https://duckduckgo.com/foo%3Bbar'
```

**Comment by boltlessengineer** [comment]
Seems to be a url encoding issue.
You can turn off default `request.hooks.encode_url` option from config
See
