### ISSUE TITLE
Response is no longer formatted after 5bcaa10

### ISSUE THREAD

**Issue by bushblade** [rest-nvim/rest.nvim#246]
After updating yesterday, the JSON and HTML responses I see are no longer formatted.
I have **jq** installed.
Here is what I see:

![Screenshot_2023-10-13_09-02-55](https://github.com/rest-nvim/rest.nvim/assets/21976188/5c9e7f54-7c2e-4fd9-b2dc-debaacc11677)

And my setup using Lazy.nvim

```lua
return {
  {
    "rest-nvim/rest.nvim",
    requires = { "nvim-lua/plenary.nvim" },
    opts = {
      result_split_in_place = true,
    },
  },
}
```

It was formatting correctly a few days ago before updating.

**Comment by NTBBloodbath** [comment]
Is there a way to see the commit you had locally before updating using lazy.nvim? That would help a lot to bisect the most recent commits, although it seems strange to me because the latest changes haven't touched that functionality iirc

**Comment by bushblade** [comment]
Hi and thanks for the reply.
Here is the log from Lazy

```
    ● rest.nvim 1.65ms  start
        5bcaa10 Add case-insensitive table lookups, and use for host and content-type. (#236) (3 days ago)
        8b62563 feat(doc): use treesitter injection (#243) (4 days ago)
        5bd5713 fix: httpResultPath match (#245) (4 days ago)
        35d949d correct spelling errors (#234) (13 days ago)
        16c1c8d Merge pull request #223 from ddomurad/ddomurad/refactor_events (3 weeks ago)
        f13ae54 Fix request hightlight (#230) (4 weeks ago)
        19cb82d Comment cleanup (9 weeks ago)
        a835f19 Refactor RestStartRequest and RestStopRequest events (9 weeks ago)
```

**Comment by bushblade** [comment]
After reverting to commit 8b62563 I now see:

![Screenshot_2023-10-13_10-01-50](https://github.com/rest-nvim/rest.nvim/assets/21976188/548364f3-726f-44a7-a2a6-85b5a2467b80)

So it appears the issue was introduced in 5bcaa1012ea8efd6093c69d2a4c67fbde760d043

**Comment by bushblade** [comment]
Looks like there are now case insensitive checks for the headers? Maybe that is the issue?

**Comment by CMOISDEAD** [comment]
I am currently experiencing the same error

**Comment by bushblade** [comment]
@CMOISDEAD If you're using Lazy.nvim you can specify a commit to use until this gets fixed:
```lua
return {
  {
    "rest-nvim/rest.nvim",
    requires = { "nvim-lua/plenary.nvim" },
    -- latest commit breaks formatting
    commit = "8b62563",
    opts = {
      result_split_in_place = true,
    },
  },
}
```

**Comment by CMOISDEAD** [comment]
@bushblade Thank you, this helps me a lot

**Comment by garrettkrohn** [comment]
Thank you bushblade!

**Comment by kevintraver** [comment]
The issue seems to be with the `res.headers` table:

https://github.com/rest-nvim/rest.nvim/blob/5bcaa1012ea8efd6093c69d2a4c67fbde760d043/lua/rest-nvim/curl/init.lua#L106

It looks like the `res.headers` table key is actually an index (number), so `"content-type"` is never getting matched in the util `M.key` function:

https://github.com/rest-nvim/rest.nvim/blob/5bcaa1012ea8efd6093c69d2a4c67fbde760d043/lua/rest-nvim/utils/init.lua#L294-L301

**Comment by NTBBloodbath** [comment]
Lately I didn't have time to debug the plugin and this behavior, thank you very much for spending some of your time and providing that information @kevintraver.

Now that I have some free time and I know what is wrong, I will proceed to patch and hopefully put an end to this malfunction as soon as possible. Apologies again to everyone who is suffering from this error, I will be more attentive with the tests!
