### ISSUE TITLE
json colors are lost when httpResult buffer is open

### ISSUE THREAD

**Issue by skoch13** [rest-nvim/rest.nvim#251]
Executing the very same request while the 'results' buffer is open results in the following:
https://github.com/rest-nvim/rest.nvim/assets/29177689/1f57e34b-89a5-4bef-ad71-6ac1615b40a5

**Comment by dimas-cyriaco** [comment]
I'm having the same problem. But with me all the text in the `httpResult` buffer looses all the highlights an become just white foreground.

**Comment by flexagoon** [comment]
Does this issue still occur? I tried running the same request twice and saw no highlighting issues

**Comment by NTBBloodbath** [comment]
Honestly I was never able to reproduce this issue. I think it is safe to close it, if it happens again and there is a reliable way to reproduce it, it can be opened again
