### ISSUE TITLE
POST file length is 0 bytes

### ISSUE THREAD

**Issue by lidaling** [rest-nvim/rest.nvim#258]
scripts bollow:

```
PUT http://localhost:9998/tika
Accept-Charset:utf-8
Accept:text/html
X-Tika-PDFsortByPosition:true

< /tmp/ope.pdf

```

**Comment by boltlessengineer** [comment]
Seems like you are tying to send a request with plain text from the non-existing file `/tmp/ope.pdf`

If you want to send a file, use multipart-form-data instead (which v3 don’t support yet)

external file syntax is used to use external file content as a raw request body.
For example:

**example.http**
```http
POST localhost:8080
Content-Type: application/json

{
  “foo”: “bar”
}
```

can be separated by two files:
**example.http**
```http
POST localhost:8080
Content-Type: application/json

< ./example.json
```

**example.json**
```json
{
  “foo”: “bar”
}
```
