### ISSUE TITLE
Cookies are not set when Set-Cookie header is received

### ISSUE THREAD

**Issue by Tesohh** [rest-nvim/rest.nvim#265]
When a Set-Cookie header is received, cookies are not set anywhere, which is something that would be extremely useful for anyone that has a service with a login.
This should be able to be done in curl using `--cookie-jar` flag.

**Comment by GustavoKatel** [comment]
is this possible with the recent release?

**Comment by NTBBloodbath** [comment]
> is this possible with the recent release?

Yes sir, I don't know how I didn't see this issue when I made reference to the others in the v2 PR ... Closing it now :)

**Comment by eeeXun** [comment]
Hi, @NTBBloodbath. How should we set cookie? I don't see any document or example.
