### ISSUE TITLE
Issue with Header Capitalization Affecting API Requests

### ISSUE THREAD

**Issue by juancarlis** [rest-nvim/rest.nvim#268]
Hello,

I am using `rest.nvim` for making API requests and have encountered an issue related to the capitalization of HTTP headers. Specifically, the issue arises with the `Api-Version` header. 

When I make a request using `rest.nvim`, the header `Api-Version` is automatically capitalized. However, the API I am interacting with is case-sensitive and expects the header in lowercase (`api-version`). This discrepancy is causing my requests to fail with a 400 error.

Here's an example of the request made by `rest.nvim`:

```bash
curl -sSL --compressed -X 'POST' -H 'Api-Version: 9' -H 'Accept: */*' -H 'Content-Type: application/json;odata.metadata=minimal;odata.streaming=true' --data-raw '{"clientId": "", "password": "somepassword*", "userName": "someusername"}' -k 'http://1.1.1.1:1000/api/v9/login'
```

And here's how I need it to be for the request to succeed:
```bash
curl -sSL --compressed -X 'POST' -H 'api-version: 9' -H 'Accept: */*' -H 'Content-Type: application/json;odata.metadata=minimal;odata.streaming=true' --data-raw '{"clientId": "", "password": "somepassword*", "userName": "someusername"}' -k 'http://1.1.1.1:1000/api/v9/login'
```

I have tried various configurations within `rest.nvim`, but it seems that there is no option available to control or prevent the capitalization of headers. 

Is there a workaround or a potential fix that could be implemented to address this issue? Any assistance or guidance on this matter would be greatly appreciated.

Thank you for your time and for developing `rest.nvim`.

**Comment by NTBBloodbath** [comment]
Hey, I think this is something that must be reported and patched in `plenary.nvim`'s repository instead. Once it is fixed there it will be also fixed here :)
