### ISSUE TITLE
How to check the request time

### ISSUE THREAD

**Issue by Ali-Aref** [rest-nvim/rest.nvim#271]
This is a great plugin, first of all thank for it.

I am wondering If I can check the request time too,
its important to know how long did my request take to get the response.

I couldn't find any option for that.

**Comment by NTBBloodbath** [comment]
Hi, thank you for such words. This is a duplicate of #147 and I've replied there for better discoverability of the implementation of such feature and how to enable it so I'd recommend you to check it out :)
