### ISSUE TITLE
Help with ipairs

### ISSUE THREAD

**Issue by JjersaR** [rest-nvim/rest.nvim#274]
I try to execute the Run command in a GET, but it won't let me, previously there were no problems.
I try to execute this GET:
![image](https://github.com/rest-nvim/rest.nvim/assets/86206596/8323ca1a-b068-4746-b215-59e079ecac3d)
And it responds to me with this error:
![image](https://github.com/rest-nvim/rest.nvim/assets/86206596/6b005e47-9d31-4a42-830c-99577e70cb77)

For clarification, the server is running and the path is correct.

Thank you for reading.

**Comment by NTBBloodbath** [comment]
Woops, I didn't expect this to happen. What's your configuration for `rest.nvim'? It seems to be wrong somewhere in the `show_statistics` value

**Comment by JjersaR** [comment]
This is my [configuration of rest](https://github.com/JjersaR/nvim/blob/main/after/plugin/rest.lua)

**Comment by NTBBloodbath** [comment]
Oh yeah, it seems to be wrong. Please take a look at the [statistics spec](https://github.com/rest-nvim/rest.nvim#statistics-spec) section in the readme.

As the configuration option documentation says, it expects a Lua table of curl `--write-out` variables, for more reference take a look at the examples in #261.

---

NTS: improve the documentation of the request statistics.
