### ISSUE TITLE
Unable to find env files in the env selector if they are defined in gitignore

### ISSUE THREAD

**Issue by skela** [rest-nvim/rest.nvim#283]
Noticed after adding *.env to .gitignore, that the selector stopped finding my environments.
Removing it again, and the environments show up in the picker.

Could you add -I as fd argument so telescope select env extension works for files in .gitignore?
Alternatively, some other way, or an example of how to make it work.

Just in case it helps,
my env files are named:
prod.env
beta.env

**Comment by lhanson** [comment]
I was just about to create an issue for exactly this but you beat me by a few minutes!

I have a similar use case; more often than not I do *not* want environment files tracked by git.
