### ISSUE TITLE
Bug(v2): winbar breaks if highlight not found

### ISSUE THREAD

**Issue by tamton-aquib** [rest-nvim/rest.nvim#290]
When calling `:Rest run cursor` (or similar commands), winbar.lua raises an error:

#### Log
<details open>
<summary>Error log:</summary>

```sh
Error executing Lua callback: ...hare/nvim/lazy/rest.nvim/lua/rest-nvim/result/winbar.lua:64: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
        [C]: in function 'format'
        ...hare/nvim/lazy/rest.nvim/lua/rest-nvim/result/winbar.lua:64: in function 'get_hl_group_fg'
        ...hare/nvim/lazy/rest.nvim/lua/rest-nvim/result/winbar.lua:75: in function 'set_hl'
        .../share/nvim/lazy/rest.nvim/lua/rest-nvim/result/init.lua:175: in function 'display_buf'
        .../share/nvim/lazy/rest.nvim/lua/rest-nvim/result/init.lua:320: in function 'write_res'
        ...al/share/nvim/lazy/rest.nvim/lua/rest-nvim/functions.lua:100: in function 'exec'
        ...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:44: in function 'impl'
        ...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:182: in function <...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:165>
```
</details>

#### Screenshot
![image](https://github.com/rest-nvim/rest.nvim/assets/77913442/12ff573e-2632-4252-92dd-e9e860c7a1f5)

#### Additional Info
- Colorscheme: [gruvbox-material](https://github.com/sainnhe/gruvbox-material)
- Using the v2 http-treesitter-parser.

**Comment by skyf0cker** [comment]
Maybe there should be a default fallback fg color when hl group is not defined and can be configured in the config.

**Comment by skyf0cker** [comment]
for others who met the same problem, you can just create a `TextInfo` and `TextMuted` highlight group as a workground.
for example:
```lua 
vim.api.nvim_set_hl(0, "TextInfo", { fg = "#e0def4" })
vim.api.nvim_set_hl(0, "TextMuted", { fg = "#6e6a86" })
 ```
 
 This works for me ;)

**Comment by NTBBloodbath** [comment]
Oh, yeah. To be honest, `TextMuted` normally when defined in the colorscheme is a link to `Comment` so we could use that group instead. I'm not completely sure about which one could fit better as a `TextInfo` replacement, perhaps something like `Constant`?

**Comment by skyf0cker** [comment]
Yes, this can definitly work, but the only worring is whether it will work well with every colorscheme. Maybe providing a config like [this](https://github.com/akinsho/bufferline.nvim/blob/64e2c5def50dfd6b6f14d96a45fa3d815a4a1eef/doc/bufferline.txt#L806) in bufferline.nvim will be better?

**Comment by NTBBloodbath** [comment]
> Yes, this can definitly work, but the only worring is whether it will work well with every colorscheme. Maybe providing a config like [this](https://github.com/akinsho/bufferline.nvim/blob/64e2c5def50dfd6b6f14d96a45fa3d815a4a1eef/doc/bufferline.txt#L806) in bufferline.nvim will be better?

Sounds good to me, some colorschemes can be a little funky sometimes with color choices so this is going to be pretty nice to have :)

**Comment by tamton-aquib** [comment]
Hi,

Maybe we could use `Statement` which is a standard highlight than `Label`?

I just checked the default colorschemes from the runtime and most of them had `Label` linked to `Statement`.
Also there are only **10/25** colorschemes having `Label`.
Whereas **24/25** colorschemes have `Statement`.
