### ISSUE TITLE
Unable to run after update

### ISSUE THREAD

**Issue by skela** [rest-nvim/rest.nvim#307]
Updated to the latest version today, but seem to be unable to get it working, even after updating my config.

This is what I have for my login.http file:

```
POST {{API}}/accounts/login HTTP/1.1
Content-Type: application/json

{
	"userName": "{{USERNAME}}",
	"password": "{{PASSWORD}}",
}

{%

local body = context.json_decode(context.result.body)
context.set_env("TOKEN", body.accessToken)

%}
```

After selecting my environment, I move the cursor to the POST API line, then run :Rest run , and it fails with some telescope errors.
![2024-03-18_15-02](https://github.com/rest-nvim/rest.nvim/assets/58268/9f8302a1-f196-4831-aed4-d0b6e08bad89)
![2024-03-18_15-02_1](https://github.com/rest-nvim/rest.nvim/assets/58268/3a51d892-5d5d-4e7c-8c58-24a3a45368ce)

**Comment by NTBBloodbath** [comment]
Hi, exactly which character of the method do you have the cursor on? I'm currently in college so I won't be able to help much right now

**Comment by NTBBloodbath** [comment]
Quick question: does your local installation have [this commit](https://github.com/rest-nvim/rest.nvim/commit/a74e940a8bab560f280f2bb7c822e4087e19dc8f)?

**Comment by skela** [comment]
I typically have the cursor on the first character of the line that has the method + url in it, so in this case it would be on the P character. But ive tested it all along that 1st line, its complaining about the same thing regardless of where i have the cursor on that line.

yes the local checkout has that commit in it:

![image](https://github.com/rest-nvim/rest.nvim/assets/58268/6deeb685-3c2a-45c9-b0ff-6f93fdb478c9)

Been thinking, it could possible be a telescope version issue?
I havent pinned my telescope, what checkout of telescope are u running?

**Comment by NTBBloodbath** [comment]
That's weird as I'm unable to reproduce the error. Could you send your `:InspectTree` output in the http file? Just to rule out that there's no problem with the parser

**Comment by skela** [comment]
![2024-03-19_08-46](https://github.com/rest-nvim/rest.nvim/assets/58268/8b522bc2-c837-407c-befd-24ce38138c4a)

**Comment by NTBBloodbath** [comment]
> ![2024-03-19_08-46](https://github.com/rest-nvim/rest.nvim/assets/58268/8b522bc2-c837-407c-befd-24ce38138c4a)
> 

Oh, there is a syntax error in the Lua scripting code, I think that could be the cause. Use `--{%` and `--%}` as the delimiters instead of `{%` and `%}` to fix the scripting to the new syntax (that change was necessary to avoid false errors with tree-sitter injected languages)

**Comment by skela** [comment]
Ah ok, i did notice that in yer docs, but i tried with and without that and it didnt seem to make a difference.
If I change it to the way you described, it still fails, but with a different error. :InspectTree looks good though.

![2024-03-19-171311_hyprshot](https://github.com/rest-nvim/rest.nvim/assets/58268/f4b48b86-b6a2-426c-a795-c57484df944b)

Seems like its complaining about my env variables, it might not be able to load them anymore. Used to in the previous versions.

For reference, i have all the http files + the env in a folder called api.

api/login.http
api/environments/prod.http.env

Have tried to run it with my cwd 1 level above the api folder (which is my git root), but i get the same error if i cd into the api folder and try to run it from there.

**Comment by skela** [comment]
Figured it out. It seems rest.nvim is a bit more sensitive to json formatting in the payloads than it used to be.
The trailing comma after the password value, caused something to fail somewhere.
This used to work, but i suppose it never should have worked (because trailing comma in json isnt really valid).

![image](https://github.com/rest-nvim/rest.nvim/assets/58268/398eb683-3e50-4804-a281-613bab669bc0)

**Comment by NTBBloodbath** [comment]
Oh woops, it seems like my vision might be failing since I hadn't noticed that trailing comma hah. And yeah, now `rest.nvim` is more strict about that since the JSON body is handled directly by the tree-sitter JSON parser, which we use to _obviously_ parse it :p

Before, if I'm not mistaken, we also used Vimscript functions for JSON, now we use `vim.json` which is a JSON parser made in C and embedded in Neovim so that could also have affected the trailing commas being valid before.

Thank you very much for your time, a pleasure to have helped :)
