### ISSUE TITLE
unable to install v2

### ISSUE THREAD

**Issue by mhuggins7278** [rest-nvim/rest.nvim#312]
On my Mac running Sonoma 14.4 I'm unable to install the luarock.nvim dependency. 

For some reason, it's unable to install Luajit.  I don't have a good error message just yet but thought someone here might be able to point me in the right direction. 
Here is my config running neovim nightly. 
```lua 
return {
  {
    "vhyrro/luarocks.nvim",
    opts = {
      rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" }, -- Specify LuaRocks packages to install
    },
    config = function()
      require("luarocks").setup({})
    end,
  },
  {
    "rest-nvim/rest.nvim",
    ft = "http",
    lazy = false,
    keys = {
      {
        "<leader>xh",
        "<cmd>Rest run<cr>",
        desc = "RestNvim",
      },
    },
    dependencies = { "luarocks.nvim" },
    config = function()
      require("rest-nvim").setup()
    end,
  },
}
```

**Comment by breenbo** [comment]
Exactly the same on my side, I have a "Using DIctionary as string" when installing luajit...

**Comment by NTBBloodbath** [comment]
Hi there!

Could you please try installing `luarocks.nvim` using the `go-away-python` which removes the `hererocks` dependency that could be failing? Take a look at `luarocks.nvim`'s author comment in [#306](https://github.com/rest-nvim/rest.nvim/issues/306#issuecomment-2007365933) for more information in case something else goes wrong or if you want to see the instructions for it

**Comment by mhuggins7278** [comment]
@NTBBloodbath that did the trick. Thank you
