### ISSUE TITLE
Authorization field seems not available

### ISSUE THREAD

**Issue by breenbo** [rest-nvim/rest.nvim#316]
Hello,

I tried a simple request, similar to the example on the repo, with a `Authorization: Bearer {{TOKEN}}`, but I'm not able to authenticate to the website.

The token is generated after login using rest-nvim, which is succesfull, I get a working token in the response.
Even if I set the token in plain text in the Authorization field, I'm not able to authenticate.
If I put the {{TOKEN}} in the url, I can see it, so setting from login and getting the TOKEN from env is working.

Seen a similar issue in a chat here, but was unable to find it again.

Thx for your awesome work.

![image](https://github.com/rest-nvim/rest.nvim/assets/19366502/eb28f9c1-37ac-4ff6-85c6-2c382c36d412)

![image](https://github.com/rest-nvim/rest.nvim/assets/19366502/e3851a6e-30fc-488c-b596-3d17147c219b)

**Comment by skela** [comment]
Have the same issues. But for me after the update, rest.nvim no longer stores the TOKEN from login, so I have to manually add it. Which is a bit frustrating.

**Comment by Rik034** [comment]
Might be related to #317

**Comment by NTBBloodbath** [comment]
Hi, this is related to [this comment in #308](https://github.com/rest-nvim/rest.nvim/issues/308#issuecomment-2007579219).

At the time of this writing, rest.nvim doesn't yet support `Authorization` headers with the new cURL implementation. It's not hard to do and it's already in progress, but there are a lot of things on the list so it may take me a day or two to push an implementation (plus the `lua-curl` library has no real documentation and I've been living reading the code of it 😢)

**Comment by skela** [comment]
@NTBBloodbath but i think the comment you tagged says its closed + its been pushed. However, and yes it might deserve its own issue i suppose - it does not seem to write into the .env file the way it used to following a successful login response. Like at all. The issue might be related to #308 though, as there was something wrong about loading env variables, perhaps its still got an issue finding the path to the env to write into it.

(alternatively the syntax has changed, but im pretty sure im doing it the way im supposed to)

**Comment by skela** [comment]
But does it mean in this current version, that it doesnt need to write the token into the env file  itself, and when u run context.set_env("TOKEN","eywhatever") it keeps it in memory, something like that?

Or does it mean context.set_env doesnt do anything at the moment.

**Comment by calvinchoy** [comment]
Is there any workaround if I need to make an call where auth basic is needed?

Maybe I am missing something.  But does this mean calls where Auth is needed is not supported in v2?

I have been trying to figure out why my calls are not working in rest.nvim and doubt whether it is an user issue or not.

**Comment by Redoxahmii** [comment]
If there are any updates on this do mention me so i can know.
I have to use a lot of Auth tokens so makes it impossible to switch.

**Comment by gegnew** [comment]
yeah hold how how are auth headers not supported? I'm really excited to use `rest.nvim`, as I've been using `roast.vim` forever and this project looks awesome, but without auth is essentially useless 😢

**Comment by Redoxahmii** [comment]
> yeah hold on how how are auth headers not supported? I'm really excited to use `rest.nvim`, as I've been using `roast.vim` forever and this project looks awesome, but without auth is essentially useless 😢
> 
> It's especially confusing because there's an auth header in `tests/`, due to which I assumed it _was_ supported

Tested it already doesn't work at this point i am intrigued to actually open it myself and see why lol

**Comment by boltlessengineer** [comment]
Closing this due to v3 release.
Should be fixed now.
