### ISSUE TITLE
<S-h> and <S-l> keybindings interfere with globally set keybinds

### ISSUE THREAD

**Issue by 8uff3r** [rest-nvim/rest.nvim#320]
I currently use these to jump between Bufferline tabs (it's actually a default keybinding of LazyVim), and when I open a rest.nvim buffer I can no longer use these keybinings to jump between bufferline tabs even after closing rest.nvim response buffer.

I think it can be solved by adding `buffer = args.buf` to [this](https://github.com/rest-nvim/rest.nvim/blob/c12c0b06ce5a09d83e79c8464f09d21fdd6b32d6/lua/rest-nvim/autocmds.lua#L33) and [this](https://github.com/rest-nvim/rest.nvim/blob/c12c0b06ce5a09d83e79c8464f09d21fdd6b32d6/lua/rest-nvim/autocmds.lua#L36) line of the source code to make these bindings buffer local too, just like the `q` and `?` binding.

**Comment by NTBBloodbath** [comment]
Fixed by #351
