### ISSUE TITLE
http client standard and intellij http client

### ISSUE THREAD

**Issue by lucax88x** [rest-nvim/rest.nvim#338]
Ciao!

I saw there's no .http standard, the only issue mentioning something was [this](https://github.com/dotnet/AspNetCore.Docs/issues/29431)

So my question was the following..

are we gonna support the standard of [intellij](https://www.jetbrains.com/help/idea/exploring-http-syntax.html), maybe using his [client](https://www.jetbrains.com/help/idea/http-client-cli.html) one day?

Or you are following another specific standard?

**Comment by boltlessengineer** [comment]
rest.nvim & `tree-sitter-http` now aims intellij standards since v3 release.

It does provide some additional semantics on top of that like `@lang=lua` for lua pre/post request scripts, but the syntax will follow intellij version.

Closing this due to `tree-sitter-http` v3 release.
