### ISSUE TITLE
Editor command

### ISSUE THREAD

**Issue by wanghui5801** [rest-nvim/rest.nvim#341]
E5108: Error executing lua: vim/_editor. lua:0: nvim_exec2(): Vim:E492: Not an editor command: Rest run

with my configuration
``` lua
...
keys = {
    {
    "\\r",
    "<Plug>RestNvim", 
    desc = "Test the current file",
  },
},
```

**Comment by boltlessengineer** [comment]
`<Plug>RestNvim` is deprecated. use `<cmd>Rest run<cr>` instead.
