### ISSUE TITLE
Get with host is working fine?

### ISSUE THREAD

**Issue by rodhash** [rest-nvim/rest.nvim#343]
### Discussed in https://github.com/rest-nvim/rest.nvim/discussions/336

<div type='discussions-op-text'>

<sup>Originally posted by **rodhash** March 24, 2024</sup>
After moving to the new version using luarocks, got some issues using GET w/ host.

<br>
Simple GET is working just fine - `Rest run` on line 3
<img width="1530" alt="image" src="https://github.com/rest-nvim/rest.nvim/assets/29671981/890411c0-d695-4c8f-b8ec-7726aee69fd1">

But GET w/ host is throwing some errors:
<img width="1904" alt="image" src="https://github.com/rest-nvim/rest.nvim/assets/29671981/5cd104d9-a882-4536-b7b2-9d0094c5ee6e">

I have all the required Treesitter parsers installed according to the README.

Am I missing anything? Perhaps something related to the newer version?

Thanks in advance</div>

**Comment by boltlessengineer** [comment]
Seems like [tree-sitter-http] issue.
Closing this due to v3 parser release. This won't happen anymore.
