### ISSUE TITLE
[Bug] Can not import file as request body

### ISSUE THREAD

**Issue by harrylowkey** [rest-nvim/rest.nvim#352]
![image](https://github.com/rest-nvim/rest.nvim/assets/39021290/2d2ef134-c7bd-4524-bf92-276baffd5cc1)
![tmux_a_-t_renyoo](https://github.com/rest-nvim/rest.nvim/assets/39021290/2b9a77a7-91c3-4ff0-b4d6-f9e2f40bfb99)

**Comment by boltlessengineer** [comment]
Closing this due to v3 release.
Feel free to reopen the issue if it still happens.
