### ISSUE TITLE
(bug): Cannot change my buffers using Shift h l

### ISSUE THREAD

**Issue by Redoxahmii** [rest-nvim/rest.nvim#353]
When you send a request and get the results afterwards you cannot switch between buffers and it stucks it there.

**Comment by daniilrozanov** [comment]
You can change this behaviour. Look at
```lua
keybinds = {
        buffer_local = false,
        prev = "H",
        next = "L",
      },
```
inside `result` in setup config example. This is default settings and `buffer_local=false` means than `HL` keys switch result panes from any active buffer (global keymaps). Set it to `true`, if you want to have `HL` switch result panes only if your current buffer is result buffer.

You probably have `HL` to switch buffers. By default, the plugin overwrites HL actions forever, once the result buffer is opened. To avoid this behaviour, set `buffer_local` to `true`, or set `prev` and `next` to some unique mappings, e.g. `<space>rp`, `<space>rn`, or any combination of that. See #350 and #351

**Comment by Redoxahmii** [comment]
> You can change this behaviour. Look at
> 
> ```lua
> keybinds = {
>         buffer_local = false,
>         prev = "H",
>         next = "L",
>       },
> ```
> 
> inside `result` in setup config example. This is default settings and `buffer_local=false` means than `HL` keys switch result panes from any active buffer (global keymaps). Set it to `true`, if you want to have `HL` switch result panes only if your current buffer is result buffer.
> 
> You probably have `HL` to switch buffers. By default, the plugin overwrites HL actions forever, once the result buffer is opened. To avoid this behaviour, set `buffer_local` to `true`, or set `prev` and `next` to some unique mappings, e.g. `<space>rp`, `<space>rn`, or any combination of that. See #350 and #351


Thanks for the quick reply.
I would recommend keeping `buffer_local` to true as default as most people would not want it to be global keymaps compared to the workflow i have seen for most people.

One last thing is is there some way the data that is fetched could be formatted or saved in a separate file ?

I have my own plugin [json-to-ts.nvim](https://github.com/redoxahmii/json-to-ts.nvim) which does a simple conversion for types in Typescript and would love if it could save the res to a file for integration with my own plugin.
Thank you for your time.

**Comment by NTBBloodbath** [comment]
> I would recommend keeping `buffer_local` to true as default as most people would not want it to be global keymaps compared to the workflow i have seen for most people.

Could you please open a PR to change this behavior if you don't mind? I agree it's saner that way :p

> One last thing is is there some way the data that is fetched could be formatted or saved in a separate file ?
> 
> I have my own plugin [json-to-ts.nvim](https://github.com/redoxahmii/json-to-ts.nvim) which does a simple conversion for types in Typescript and would love if it could save the res to a file for integration with my own plugin.
> Thank you for your time. I will close this issue after you reply.

Not right now, could you open a separate issue for that as a feature request? That could help to keep track of it :p

**Comment by Redoxahmii** [comment]
> Could you please open a PR to change this behavior if you don't mind? I agree it's saner that way :p
>
Created a [PR](https://github.com/rest-nvim/rest.nvim/pull/358) which changes this behavior.
> 
> Not right now, could you open a separate issue for that as a feature request? That could help to keep track of it :p

Also created a [Feature](https://github.com/rest-nvim/rest.nvim/issues/359) request for saving files.
