### ISSUE TITLE
telescope extension not working

### ISSUE THREAD

**Issue by Phantasimay** [rest-nvim/rest.nvim#362]
hi i am new of using this plugin. i was install this plugin as default step by step. but when i implement rest.nvim on telescope as extension. it dont work. can you give a guide to fix it?

**Comment by alejandroo-pc** [comment]
Hey @Phantasimay would you mind sharing your config with the plugin?

**Comment by erichydrick** [comment]
I get this error from the require("telescope").load_extension("rest") line in my telescope plugin file:

![Screenshot_2024-06-12_08-13-09](https://github.com/rest-nvim/rest.nvim/assets/1953794/87d8a768-f992-40c4-ba0b-a5be4ce65b77)
![telescope](https://github.com/rest-nvim/rest.nvim/assets/1953794/d41f7ca4-9ae9-4045-ab48-f7759ab125c8)
