### ISSUE TITLE
How to pretty print a json response?

### ISSUE THREAD

**Issue by gzfrozen** [rest-nvim/rest.nvim#363]
I set the plugin with the default formatter setting. `jq` is installed.

I see the json response is not pretty printed as the example shows in the `README.md`
![image](https://github.com/rest-nvim/rest.nvim/assets/39619255/caf58ec6-30df-419f-b069-52aeeac2caa8)

Do I need more config?

**Comment by daniilrozanov** [comment]
I'm not 100% sure that this could be the reason, but maybe your server does not set the application/json field in the header

**Comment by gzfrozen** [comment]
@daniilrozanov 
Thank you for your reply.

Do you mean the `content-type` header in response? I think it is already set to `application/json`.
<img width="641" alt="image" src="https://github.com/rest-nvim/rest.nvim/assets/39619255/6668d532-70d4-4b8e-8be3-7d52925cdc40">

**Comment by daniilrozanov** [comment]
Try to update your plugin. Recently it was case sensitive in relation to the `Content-Type` field

**Comment by gzfrozen** [comment]
@daniilrozanov 
Wow, thanks. The problem is solved after the updating.🎉
