### ISSUE TITLE
Can't post form-urlencoded data

### ISSUE THREAD

**Issue by gegnew** [rest-nvim/rest.nvim#364]
this is just `curl -XPOST <url> -d 'key=val` but it doesn't seem possible with `rest.nvim`. Is there a solution to this?

Referenced disussion:

_Originally posted by @jwhoami in https://github.com/rest-nvim/rest.nvim/discussions/259_

**Comment by Drowze** [comment]
Also going through the same. I'd like to use this for quick prototyping - but unfortunately not supporting `application/x-www-form-urlencoded` is a major block for me 🤔 

For instance, I've been trying with:
```
POST https://login.microsoftonline.com/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/oauth2/v2.0/token
content-type: application/x-www-form-urlencoded

scope=https://graph.microsoft.com/.default&client_id=ffffffff-gggg-hhhh-iiii-jjjjjjjjjjjj&client_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&grant_type=client_credentials
```

**Comment by boltlessengineer** [comment]
Closing this due to v3 release of [tree-sitter-http](https://github.com/rest-nvim/rest.nvim).
Now rest.nvim officially supports `form-urlencoded` body type.
