### ISSUE TITLE
TreeSitter highlighting for response

### ISSUE THREAD

**Issue by disrupted** [rest-nvim/rest.nvim#366]
Why does the response buffer use the `httpResult` filetype, not `http` like the request buffer? I feel like it would be nicer to use the same TreeSitter parser for the response.

**Comment by NTBBloodbath** [comment]
It is not possible due to the nature of the results buffer content, at least not without introducing breaking changes and more complexity.

**Comment by disrupted** [comment]
could you elaborate what are the breaking changes? I just tested it locally by running `:set ft=http`. After making the buffer modifiable (`:set modifiable`) and manually deleting the comments `#+RES` and `#+END` (not sure what's the purpose of those). It works well for me with a JSON body

**Comment by NTBBloodbath** [comment]
> could you elaborate what are the breaking changes? I just tested it locally by running `:set ft=http`. After making the buffer modifiable (`:set modifiable`) and manually deleting the comments `#+RES` and `#+END` (not sure what's the purpose of those). It works well for me with a JSON body

Does the `HTTP/X.X OK` like works well too? Also check `:InspectTree` output to look for error nodes. If nothing is wrong, we could make the change without much problem, although I'm worried about what the parser might spit out when the response to a request is binary, or in case of returning an image

**Comment by disrupted** [comment]
Good point, the second line gets falsely parsed as request. This would either need to be fixed in the parser, or perhaps we would need a separate parser (based on `http`) since it's not part of the http filetype.

**Comment by NTBBloodbath** [comment]
Sounds good to me, hope we can achieve something in the short term!

**Comment by boltlessengineer** [comment]
Closing this due to v3 release.
`rest.nvim` now use `tree-sitter-http` to highlight the result UI.
