### ISSUE TITLE
No longer working with cookies.

### ISSUE THREAD

**Issue by bushblade** [rest-nvim/rest.nvim#368]
The plugin no longer works with saving or using a cookie in the request.

This request used to work for me:

```http
# Login a user
POST {{BASE_URL}}/api/users/auth
Content-Type: application/json

-c backend/http/cookies

{
  "email": "john@email.com",
  "password": "123456"
}
```

But now I get the following response:
```
POST http://localhost:5000/api/users/auth
HTTP/1.1 400 Bad Request

#+RES

#+END
```

The same request works in Postman and Insomnia and in Curl:

![Screenshot_2024-04-18_12-09-51](https://github.com/rest-nvim/rest.nvim/assets/21976188/b73cd8f1-a0cd-41be-9c6b-f2e15fee70bb)

And if I remove the `-c backend/http/cookies` then I do get a good response in rest-nvim but obviously no cookie was saved.

**Comment by boltlessengineer** [comment]
Closing this due to v3 release.
Now rest.nvim officially supports cookies following RFC standards.
You can edit cookies file with `:Rest cookies` command.
