### ISSUE TITLE
Feature Request: Notifications

### ISSUE THREAD

**Issue by kevintraver** [rest-nvim/rest.nvim#381]
**Feature Request:**

Use `vim.notify` on request start and request completed, or if there is an error.

Could be an opt-in feature.

Happy to help with a PR.

Thanks for the awesome plugin!

**Comment by NTBBloodbath** [comment]
Hey!

Currently I have many things on my list, unfortunately I am in exam weeks and I have not been able to do any of the project yet. I would gladly accept a PR for this, sounds really useful :)

Ps: personally I would make it opt-out instead, as receiving a notification in Neovim isn't an obtrusive thing and it could come handy to have it by default. Perhaps you could use a fidget implementation instead like what `rocks.nvim` does?

**Comment by teto** [comment]
in v1 we had a system of hooks just for this purpose. If it is still available in latest version, I would recommand to look into it so you dont need upstreaming.
I would also suggesto add a threshold: if the request is instant, no need for notifs

**Comment by boltlessengineer** [comment]
Closing this due to v3 release. rest.nvim now supports both `fidget.nvim` and `vim.notify` as an opt-in feature.

It will notify you with `vim.notify` when request failed. General request progress will be shown from `fidget.nvim`
