### ISSUE TITLE
Can't parse the simply http file

### ISSUE THREAD

**Issue by LintaoAmons** [rest-nvim/rest.nvim#391]
<img width="1530" alt="image" src="https://github.com/rest-nvim/rest.nvim/assets/95092244/cd4fa63f-7234-41e2-94e8-9ce498866da5">

```http
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "name",
    "password": "password"
}

###
GET http://localhost:3000/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEoxNzE3MjI0MjgyfQ.MUwXnaJ8YVVauG_jN3cNDVvpSZdmJMfQSc-zy2bR5S4
```

I also tried the same file with IDEA, it should be able to trigger the request
<img width="511" alt="image" src="https://github.com/rest-nvim/rest.nvim/assets/95092244/e062e66b-e84e-470a-899d-a878957dfe6c">

**Comment by tg0h** [comment]
i have the same problem - see https://github.com/rest-nvim/rest.nvim/issues/389 for a workaround

**Comment by boltlessengineer** [comment]
Seems like [tree-sitter-http](https://github.com/rest-nvim/tree-sitter-http) issue.
Closing this due to v3 release. Feel free to reopen the issue if it still happens
