### ISSUE TITLE
Unbale to use rest.nvim in windows10

### ISSUE THREAD

**Issue by CengsBlanky** [rest-nvim/rest.nvim#393]
I have installed rest.nvim under Linux and it workd pretty fine(but it also need some extra steps to solve `luarocks` problem), but due to poor support of luarocks for Windows, `lua-curl` just can't be installed, thus this plugin can not work under windows, I can't switch to Linux or WSL because Windows10 is my only option at workplace

BTW, here why I can't install `lua-curl':
```
Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luarocks.org/repositories/rocks

Error: No results matching query were found.
```

I have tried
1. 'all-in-one' lua for Windows
2. just rely on 'luarocks.nvim'
3. install luarocks separately and use it to install and compile `lua-curl`(by install 32/64 curl for windows and provide its header file), and of course, luarocks compilation break down

none of these method worked

I understand it is not the plugin's problem, but luarocks did a pretty bad job about Windows(even for Linux because a package manager needs to rely on a static curl directory to complie lua-curl), we may not depend too much on it(it's just my personal thought)

Anyway, thanks for your work, rest.nvim is by far the most REST cli I would like to try during my real work, it provides enough flexibility for my requirement

**Comment by CengsBlanky** [comment]
Any one succeeded installed rest.nvim under Windows PowerShell would be greatly appreciated if you can share you config or procedures!

**Comment by Alberto-B-Lopez** [comment]
On the same boat was able to get lua-curl to install but rest.nvim still doesn't recognize it. Currently it's in the folder structure luarock/current/rocks/lua-curl.

**Comment by boltlessengineer** [comment]
Since v3 release, rest.nvim doesn’t require `lua-curl` anymore, So this issue seems to be resolved now.
