### ISSUE TITLE
Async task failed without callback

### ISSUE THREAD

**Issue by abanseka** [rest-nvim/rest.nvim#396]
### ERROR LOG PREVIEW
![Screenshot from 2024-06-19 20-21-59](https://github.com/rest-nvim/rest.nvim/assets/78860665/3a3ea532-5389-4ff2-ad35-d449dcd83210)

**Comment by boltlessengineer** [comment]
Closing this due to v3 release.
rest.nvim don’t use `lua-curl` anymore so this won’t happen in v3 version.
