### ISSUE TITLE
Env var not working properly 

### ISSUE THREAD

**Issue by mrlectus** [rest-nvim/rest.nvim#422]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.10.1

### Operating system/version

Linux

### Actual behavior

Create a .env file and place in the environment
```bash
BASE_URL="http://127.0.0.1:4000"
```
calling it in the *.http file

```http
POST {{BASE_URL}}/ping
Content-Type: application/json

{
  "ping": "PONG!!"
}
```

In the response screen, I can see this
`POST %2522http%253a%252f%252f127.0.0.1%253a4000%2522/ping`

it also doesn't work cause the correct response is pong! but i see Loading

### Expected behavior

Response screen should show the correct URL and it should work

### Steps to reproduce

I don't know

### Repro (`lazy.nvim`)

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        "rest-nvim/rest.nvim",
        {
            "nvim-treesitter/nvim-treesitter",
            build = ":TSUpdate",
            main = "nvim-treesitter.configs",
            opts = {
                ensure_installed = { "http" },
                sync_install = false,
                highlight = { enable = true },
                indent = { enable = true },
            },
        },
    },
})
```

**Comment by boltlessengineer** [comment]
Should be fixed now (sorry, I forgot to mention it in commits)
