### ISSUE TITLE
Rest run error: Invalid node type "section"

### ISSUE THREAD

**Issue by apechinsky** [rest-nvim/rest.nvim#445]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.1

### Operating system/version

Arch Linux, 6.10.6-arch1-1

### Actual behavior

Getting the following error when executing GET request:
```
Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 1:2. Invalid node type "section":
(section
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'parse'
        .../min-plugin/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:19: in main chunk
        [C]: in function 'require'
        ...vims/min-plugin/lazy/rest.nvim/lua/rest-nvim/request.lua:5: in main chunk
        [C]: in function 'request'
        ...ims/min-plugin/lazy/rest.nvim/lua/rest-nvim/commands.lua:125: in function 'impl'
        ...ims/min-plugin/lazy/rest.nvim/lua/rest-nvim/commands.lua:309: in function <...ims/min-plugin/lazy/rest.nvim/lua/rest-nvim/commands.lua:297>
```

### Expected behavior

Successful execution.

### Steps to reproduce

- Create file test.http with the following content:
```
GET https://www.youtube.com/
```
- Run ex command: `Rest run`
Result: the error 

### Repro (`lazy.nvim`)

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out, "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = " "

require("lazy").setup({
    spec = {
        {
            'nvim-treesitter/nvim-treesitter',
            config = function()

                require 'nvim-treesitter.configs'.setup {
                    ensure_installed = { "c", "lua", "vim", "vimdoc", "http" },
                    sync_install = false,
                    auto_install = false,
                    ignore_install = { "javascript" },
                    highlight = {
                        enable = true,
                        additional_vim_regex_highlighting = false,
                    },
                }
            end,
        },

        {
            "rest-nvim/rest.nvim",
        }
    },
    checker = { enabled = true },
})
```

**Comment by boltlessengineer** [comment]
Can you provide the output of `:InspectTree` in http files?
Seems like your installed tree-sitter `http` parser is outdated.
Try reinstalling it with `:TSUninstall http` and `:TSInstall http`

**Comment by chardskarth** [comment]
I experienced this as well. 

I got this fixed by manually installing tree-sitter-http scm-1 version. 

I use luarocks.nvim and I had to manually add "--dev" so it can resolve scm-1 version.

**Comment by boltlessengineer** [comment]
@chardskarth Yes, you need to install `scm` version, I’m going to ask mrcjkb this weekend if we can version the tree-sitter-http manually outside of [NURR](https://github.com/nvim-neorocks/nurr) or if we can upgrade the version from NURR. This will make installing rest.nvim way easier because then users just need to do `:Rocks install rest.nvim` or put `{ ”rest-nvim/rest.nvim” }` in lazy spec.

btw why do you install http parser from `luarocks.nvim`? You don’t use neither `nvim-treesitter`, `rocks-treesitter.nvim` nor `lazy.nvim`?
I didn’t explicitly say about `scm-1` version and just provide the install method for `rocks.nvim` and `nvim-treesitter` in README because I thought those are all major methods I know to install treesitter parsers for Neovim.
What plugin manager do you use? Do you use parser manager like `nvim-treesitter`?

**Comment by boltlessengineer** [comment]
@apechinsky you definitely have outdated http parser. Try updating `nvim-treesitter` so it can install the latest http parser.

**Comment by chardskarth** [comment]
> btw why do you install http parser from `luarocks.nvim`? You don’t use neither `nvim-treesitter`, `rocks-treesitter.nvim` nor `lazy.nvim`? I didn’t explicitly say about `scm-1` version and just provide the install method for `rocks.nvim` and `nvim-treesitter` in README because I thought those are all major methods I know to install treesitter parsers for Neovim. What plugin manager do you use? Do you use parser manager like `nvim-treesitter`?

I didn't know I had to update nvim-treesitter. Simply installing tree-sitter-http wasn't working for me so I figured the latest one should work for me. Just worked.

**Comment by boltlessengineer** [comment]
Closing this issue as this seems to be a http parser version issue which should be easily fixed by `:TSUpdate http` or `:Rocks isntall tree-sitter-http dev`

**Comment by apechinsky** [comment]
I've updated treesitter and parser but the problem remains.

**Comment by boltlessengineer** [comment]
@apechinsky can you test with this minimal config?
Save this snippet as `repro.lua` and run `nvim -u repro.lua example.http`. It will create temporary `.repro/` directory to have fresh installation of all plugins/parsers and save all caches/states there.

```lua

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        {
          lazy = false,
          "rest-nvim/rest.nvim"
        },
        {
            "nvim-treesitter/nvim-treesitter",
            build = ":TSUpdate",
            main = "nvim-treesitter.configs",
            opts = {
                ensure_installed = { "http" },
                sync_install = false,
                highlight = { enable = true },
                indent = { enable = true },
            },
        },
    },
})
```

**Comment by apechinsky** [comment]
I've just updated the plugin, and the problem is gone now.
