### ISSUE TITLE
Feature: update required lua version up to actual 5.4

### ISSUE THREAD

**Issue by tony-sol** [rest-nvim/rest.nvim#477]
### Issues

- [X] I have checked [existing issues](https://github.com/rest-nvim/rest.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

According to dependencies, rest.nvim requires `"lua >= 5.1, < 5.4"`, but while i'm trying to use it with lua 5.3.6 it always causes an warning

```
`lua` version `5.1` needed, but found `Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio`
```

**Comment by boltlessengineer** [comment]
That requirement is actually incorrect. I will fix that.
Neovim only supports `lua 5.1` via LuaJIT (`:h lua`).
You need `lua 5.1` in your system to properly install this plugin via luarocks.

Both `lazy.nvim` and `rocks.nvim` should handle this lua dependency automatically.
What neovim plugin manager are you using to install `rest.nvim`?

**Comment by tony-sol** [comment]
> Both `lazy.nvim` and `rocks.nvim` should handle this lua dependency automatically. What neovim plugin manager are you using to install `rest.nvim`?

`lazy.nvim`

**Comment by boltlessengineer** [comment]
You can 1) manually install `lua5.1` in your machine or 2) force `lazy.nvim` to use `hererocks` to install all `lua` & `luarocks` by itself.

For second method, your `lazy.nvim` setup will look like this:

```lua
require("lazy").setup({
  spec = {
    -- your plugin specs
  },
  rocks = {
    enabled = true,
    hererocks = true,
  },
})
```

**Comment by tony-sol** [comment]
Thx, i'll switch to 5.1, btw is 5.1.5 ok? Is it bounded only to minor version, or also to patch?

**Comment by boltlessengineer** [comment]
`lua` in your system is only used to install the plugin no many stuffs happening there. `5.1.5` is fine, I'm also using that version.

**Comment by boltlessengineer** [comment]
@dzintars This plugin relies on lua 5.1 because that is the version Neovim is using.

> Neovim only supports lua 5.1 via LuaJIT (:h lua)

You don't need to downgrade lua in your system. This plugin can work without matching lua version from system level.
Can you describe the issue while installing this plugin? So that I can help you properly.

**Comment by dzintars** [comment]
@boltlessengineer 

This is the original gibberish:
![image](https://github.com/user-attachments/assets/7bd96c09-bda5-4ab7-8b95-8ffcae6d699f)

This is what's on my system:
![image](https://github.com/user-attachments/assets/d46a4ef6-db02-42b1-ba66-f784860de0c6)

The only way to get this plugin working is something like this:
![image](https://github.com/user-attachments/assets/f8bf5879-3490-476a-9ddf-8783c0f0a3d6)

We are switching to outdated Lua 5.1 version.

Then, we need to mess up the `luarocks` because it complains about _something something_.

```bash
cd /opt/luarocks-3.11.1
./configure --with-lua-include=/opt/lua-5.1.5/src
make
sudo make install
```
We are explicitly pointing to the right `lua.h` headers there.

Only after these nasty tweaks I were able to install this plugin like a normal human being. :)

**Comment by boltlessengineer** [comment]
@dzintars glad that you were able to install the plugin at the end.

You don't need to fix lua/luarocks installation in your machine if you are using `lazy.nvim`.
`lazy.nvim` can handle those automatically.
As your first screenshot says:

> - enable `hererocks` with `opts.rocks.hererocks = true`

with this option, `lazy.nvim` will install both lua & luarocks required to install this plugin only for Neovim, so you don't need to change system installed lua version.

**Comment by tony-sol** [comment]
The only thing i cant understand is - if nvim uses lua5.1 "under the hood" (which is true), why plugins use a system-installed lua, instead bundled one, and why the only rest.nvim keeps complaining about lua version

**Comment by boltlessengineer** [comment]
@tony-sol It's not `rest.nvim` complaining about the lua version. It's `luarocks` which requires system installed lua5.1 to install rockspec packages.

**Comment by dzintars** [comment]
So... this plugin is using `luarocks` to get deps and build itself? Because Nvim runs under Lua 5.1, `rest.nvim` should be also built against the same Lua version (5.1)? Is this right?

**Comment by boltlessengineer** [comment]
@dzintars Plugin managers like `lazy.nvim` or `rocks.nvim` are using `luarocks` to get dependencies of `rest.nvim` when installing it. Lua 5.1 is also required to read the `rockspec` file defining all dependencies and post-install scripts in each lua packages.
