### ISSUE TITLE
Lazy.nvim installation does not work

### ISSUE THREAD

**Issue by Frying7415** [rest-nvim/rest.nvim#493]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.10.2

### Operating system/version

Fedora 40

### Actual behavior

Upon installation raises a warning about missing dependencies (if this one is resolved, complains about mimetypes which I cant figure out how to resolve). 
![image](https://github.com/user-attachments/assets/deeb6cb2-9cc0-49ed-9056-434f1f4bfe89)

Trying to run a request raises error
![image](https://github.com/user-attachments/assets/32c8a99b-5569-4975-8963-364ab1734d89)
![image](https://github.com/user-attachments/assets/a5552f95-a179-442e-ad4e-0a0531aeebd9)

### Expected behavior

The thing works after you follow installation steps in README.md?

### Steps to reproduce

Install with Lazy.nvim following the README.md

### Repro (`lazy.nvim`)

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        "rest-nvim/rest.nvim",
        {
            "nvim-treesitter/nvim-treesitter",
            build = ":TSUpdate",
            main = "nvim-treesitter.configs",
            opts = {
                ensure_installed = { "http" },
                sync_install = false,
                highlight = { enable = true },
                indent = { enable = true },
            },
        },
    },
})
```

**Comment by boltlessengineer** [comment]
duplicated of #484 for tree-sitter query issue. Seems like you have legacy tree-sitter parser.

For lazy.nvim installation issue, you need `rockspec` support enabled in your lazy.nvim setup. Which is enabled by default, so check if you have legacy lazy.nvim version.
Check the result of `:checkhealth lazy` and see if everything is fine.

**Comment by Frying7415** [comment]
The screenshot of the result for that command is in my previous comment. This one
![image](https://github.com/user-attachments/assets/aed1d7e6-351c-4c18-be90-58f90856b4fc)

**Comment by boltlessengineer** [comment]
@Frying7415 Sorry for misreading your previous comment, my bad.
Seems like your installed `lazy.nvim` version doesn't support `luarocks`.

I recommend you to update `lazy.nvim` to more recent version.

**Comment by Frying7415** [comment]
@boltlessengineer gotcha, lunarvim pins versions of core plugins and updating lazy from 10.20.3 to latest broke quite a few things lol
I'll look into fixing those or switching to lvim alternatives, but this issue is certainly resolved. Thanks!
