### ISSUE TITLE
Feature: add option to set filetype

### ISSUE THREAD

**Issue by mageOfstructs** [rest-nvim/rest.nvim#495]
### Issues

- [X] I have checked [existing issues](https://github.com/rest-nvim/rest.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

The .http type check is currently hardcoded. Could this be made configurable, so the plugin will at least attempt to parse text in other files (like .rest)?

**Comment by boltlessengineer** [comment]
Sorry for late reply! You can manually add `rest` filetype in your config like this, no need to add an option in this plugin ;)

**`after/ftdetect/http.lua`**
```lua
vim.filetype.add({
    extension = {
        rest = "http",
    },
})
```

See `:h new-filetype` for more info.
