### ISSUE TITLE
Error parsing bug

### ISSUE THREAD

**Issue by timsofteng** [rest-nvim/rest.nvim#67]
Hello. I faced up with parsing error bug.
Look at the response of the `rest.nvim`
![image](https://user-images.githubusercontent.com/51912173/133229254-1c550e4a-ab6e-48ca-906b-dbda8b027452.png)
and now look at the response of the same request in insomnia:
![image](https://user-images.githubusercontent.com/51912173/133229377-12a4eb89-fac2-4454-9bfb-21056eecf54f.png)

**Comment by NTBBloodbath** [comment]
Hey, can you please add an example http file to have a better understanding of what are you trying to do? Remember to remove sensitive data if you need to.

Also if you could explain a bit more about what do you mean with the bug it would be great, right now I understand that the raw message is very different and our makes no sense compared with insomnia one, am I right?

Regards

**Comment by timsofteng** [comment]
Yes, you are right.
Here is the request.

![image](https://user-images.githubusercontent.com/51912173/133231399-9384f629-511a-4cd3-b441-b673b320dfb2.png)

**Comment by timsofteng** [comment]
Hello. Have you catch it?

**Comment by NTBBloodbath** [comment]
Hi, sorry for the late reply.

It's gonna take a bit of time to me, there's a ton of stuff to debug to know how to handle these errors and I don't know where can I test the authorization things because I currently don't have a local backend haha, it would be really useful if you know a site to test them

**Comment by timsofteng** [comment]
You may probably start some local service and raise 401 error with some text.

I believe it's some problem with text reading.
In my example column 8 is space symbol. Maybe pfoblem is there...

**Comment by jens1205** [comment]
In my opinion the webservice has a bug. You are receiving the text `invalid or missing token`, but at the same time the content-type header says: `content-type: application/json'. Obiously the plain text is not json.

Try `echo "invalid or missing token" | jq` and you get the same error you see in rest.nvim: `parse error: Invalid numeric literal at line 1, column 8`

So, this issue should be closed and the webservice must be fixed. Either return the error in valid JSON, or don't pretend to send back json, but set the content-type to text.

**Comment by timsofteng** [comment]
> In my opinion the webservice has a bug. You are receiving the text `invalid or missing token`, but at the same time the content-type header says: `content-type: application/json'. Obiously the plain text is not json.
> 
> Try `echo "invalid or missing token" | jq` and you get the same error you see in rest.nvim: `parse error: Invalid numeric literal at line 1, column 8`
> 
> So, this issue should be closed and the webservice must be fixed. Either return the error in valid JSON, or don't pretend to send back json, but set the content-type to text.

Ok, looks like you are right.
BUT
I guess plugin should display content any way but maybe with some error or hint like "content and body are not the same type!".
It is tool for development. I need to body anyway.

**Comment by NTBBloodbath** [comment]
Hmm you're right. Actually the error message that you've proposed makes more sense than a JQ parsing error. I'm gonna do some tests today.

**Comment by timsofteng** [comment]
Hello. Any updates?

**Comment by timsofteng** [comment]
@NTBBloodbath
