### ISSUE TITLE
Syntax highlight for {{URL}}, and global header

### ISSUE THREAD

**Issue by dakennguyen** [rest-nvim/rest.nvim#74]
Hi, I have something like this in my `http` file:
![image](https://user-images.githubusercontent.com/18320285/136497973-7e99ba3f-8375-4474-baab-1701b1a87745.png)
Some issues/suggestions that I have:
1. Syntax highlight only works if the request begin with `http://` or `https://`. Could we have syntax highlight even if the env variable is at the beginning as well?
2. It's nice that we have `global header`, so I don't have to repeat `Jwt-Token` every time (sometimes I have more headers, so you understand the inconvenient)

Thank you so much for your time!

**Comment by RaafatTurki** [comment]
I came to make an issue about those 2 exact things, I hope this gets attention.

**Comment by NTBBloodbath** [comment]
Syntax highlighting issue was resolved by [tree-sitter-http#3](https://github.com/rest-nvim/tree-sitter-http/pull/3) PR.

About global headers I'll take a look at what RFC 2616 offers regarding to this scope. If there's nothing about it in the specs I'll make a special syntax for this.

**Comment by sigzegv** [comment]
any news about this feature? It sounds really usefull for me. Also it would be usefull not having to inform the URL on each request, put take the global one for the active file.
