### ISSUE TITLE
packer: opt=true causes rest.nvim to fail

### ISSUE THREAD

**Issue by jceb** [rest-nvim/rest.nvim#78]
I set up rest.nvim as an optional dependency like this:

```lua
    use({
        "NTBBloodbath/rest.nvim",
        requires = { "nvim-lua/plenary.nvim" },
        opt = true,
        ft = { "http" },
        config = function()
            require("rest-nvim").setup({
                result_split_horizontal = false,
            })
            vim.cmd([[
            au FileType http nmap <buffer> <silent> <C-j> <Plug>RestNvim
            ]])
        end,
    })
```

When I open a file, set the file type to `http` and press `<C-j>` I get the following error:

```
Error executing luv callback:
...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:614: ENOENT: no such file or directory: /tmp/plenary_curl_b3524790.headers
```

With `opt=false` everything works fine.

**Comment by lkoning** [comment]
I am not exactly sure what you are trying to do here...but maybe this helps a bit. I don't use Packer but still have setup rest.nvim as an optional plugin. Don't really know if this improves loading time or performance. It's mere an experiment:

Install the plugin with Paq, Packer should be quite similar I guess:
`require("paq-nvim")({
....
	{ "NTBBloodbath/rest.nvim", opt = true },
....
})
`

Then in a module required from init.lua:
`vim.cmd([[ au BufEnter *.http call v:lua.require("plugins.rest").loadRestClient() ]])

local M = {}

function M.loadRestClient()
	if vim.g.loaded_rest_nvim ~= 1 then
		vim.cmd([[ packadd rest.nvim ]])
		require("rest-nvim").setup({
			result_split_horizontal = false,
			skip_ssl_verification = false,
			highlight = { enabled = true, timeout = 150 },
			jump_to_request = false,
		})
		vim.api.nvim_set_keymap("n", "<leader>r", "<Plug>RestNvim", { nowait = true })
		vim.api.nvim_set_keymap("n", "<leader>pr", "<Plug>RestNvimPreview", { nowait = true })
		vim.cmd("command! RestNvim lua require('rest-nvim').run()")
		vim.cmd("command! RestNvimPreview lua require('rest-nvim').run(true)")
	end
end

return M
`

This seems to load the plugin correctly when opening a .http file. For other files the commands and mappings are not available.

**Comment by teto** [comment]
feel free to reopen if you still have the issue.
