### ISSUE TITLE
migration from vim-rest-console

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#82]
I come from https://github.com/diepm/vim-rest-console which I liked but this plugin looks more promising (treesitter support + I prefer hacking on lua).

What I like about vim-rest-console is that I can have several requests in the same file + I dont have to prefix the request with a variable let's say {{ URL }}/.health.
Is that possible with rest.nvim ? Or should I prefix all my requests with `{{URL}}` ?
```
# use with vim-rest-console
# Hit the trigger key (<C-j> by default).
http://localhost:2000

modelid = 0d6cf41efd5b3b8f55d4feded55ca367fd8eea0f0eff9305e8fcaf6f7650188d
scoreid = 9b5da9bc6538e1c0e3f955b5f49fc478cd18d94d95cbce8d0e9d9b7cac849dcd

jobid = 410de781-34e0-53b5-855a-7bffcb3bce17
--


--
# Healthcheck
GET /.health

--
# Healthcheck
GET /openapi.json
```

**Comment by teto** [comment]
Some comment I defined my .env as 
`URL = http://localhost:2000` and it triggered sthg like `|| ...ack-dir/pack/nix/start/plenary.nvim/lua/plenary/curl.lua:248: get %7B%7B - curl error exit_code=6 stderr={ "curl: (6) Could not resolve host: %7B%7B" }`
removing spaces fixed it `URL=http://localhost:2000`. May be worth adding to the `rest-nvim-usage-environment-variables` help ?

**Comment by NTBBloodbath** [comment]
Hi,

> What I like about vim-rest-console is that I can have several requests in the same file + I dont have to prefix the request with a variable let's say {{ URL }}/.health.
Is that possible with rest.nvim ? Or should I prefix all my requests with `{{URL}}` ?

We follow RFC 2616 request format with a few extra niceties like variables and external json bodies, so the format used in `vim-rest-console` is not valid and you should prefix all your requests with the URL environment variable.

**Comment by NTBBloodbath** [comment]
> Some comment I defined my .env as 
> `URL = http://localhost:2000` and it triggered sthg like `|| ...ack-dir/pack/nix/start/plenary.nvim/lua/plenary/curl.lua:248: get %7B%7B - curl error exit_code=6 stderr={ "curl: (6) Could not resolve host: %7B%7B" }`
> removing spaces fixed it `URL=http://localhost:2000`. May be worth adding to the `rest-nvim-usage-environment-variables` help ?

I think that yeah it's worth, and could help newbies and people not very familiarized with environment files.

> EDIT: also the example in `rest-nvim-quick-start` could be improved by putting a full example: I've had to check https://github.com/NTBBloodbath/rest.nvim/blob/main/tests/post_create_user.http to see the full syntax

Got it, I'll do it today after work if possible. Thanks per pointing this out :)

**Comment by teto** [comment]
> We follow RFC 2616 request format with a few extra niceties like variables and external json bodies, so the format used in vim-rest-console is not valid and you should prefix all your requests with the URL environment variable.

Ok thanks, I will miss that peculiar feature but I understand adhering to the standard.

Feel free to close this.

**Comment by teto** [comment]
running `lua require('rest-nvim').run(true)`, I noticed the headers were not escaped: 
```
curl -sSL -D /tmp/plenary_curl_800543fa.headers --compressed -X POST -H Accept:  application/json -H Content-Type:  application/json --data-raw {"filter": {"tag": "And", "contents": []}} http://localhost:2000/my_result
```
I am not well versed in REST so maybe it's not possible to have a space after Accept ? but when I quote the following it works fine. Even the --data-raw part is not quoted which looks more surprising to me. Could it be a shell issue ? I run zsh

**Comment by teto** [comment]
I looked at the code a bit and plenary seems to correctly call curl, I suppose it's just the printing of the command that is imperfect. Would be cool to improve still.
