### ISSUE TITLE
pass credentials for http basic auth

### ISSUE THREAD

**Issue by joshuali925** [rest-nvim/rest.nvim#89]
Using curl, credentials can be passed with the `-u <user>:<pass>` flag:

```
curl -u guest:guest https://jigsaw.w3.org/HTTP/Basic/
```

But I didn't find the corresponding option here, how to do the same in rest.nvim? thanks

---

I took another look and seems auth is not supported yet? A simple fix would be to also exclude `@` when encoding url
https://github.com/NTBBloodbath/rest.nvim/blob/3ab950fe88cf836c83fa15a10e386ccd5f6aa1cb/lua/rest-nvim/utils/init.lua#L273-L274

According to https://stackoverflow.com/a/19737890 `@` can be used directly in url, and then this will work

```
GET https://guest:guest@jigsaw.w3.org/HTTP/Basic/
```

**Comment by NTBBloodbath** [comment]
Hi, thank you so much for the information. Being honest I found this too a few days ago when trying out an API.

I have read plenary's curl wrapper source again and it seems that they have auth as an undocummented feature. I'll start doing an implementation in our side to interact with that "hidden" feature but also include the `@` in url so user will have both options :)
